### ISSUE TITLE
using this module as json to csv converter

### ISSUE THREAD

**Issue by mderazon** [adaltas/node-csv-stringify#1]
Hi, I am trying to use this to convert an array of flat json objects to csv file.

I am using the pipe example. The output I get do not contain headers (keys of the objects)

Is there any way to use this module for this functionality ?

Thanks

**Comment by sunyonggang** [comment]
i am sorry, but i am writing a module for download ElasticSearch's data into csv, but i met a problem.
The data was not uniformed, it could missing some field in one row, also it cloud add some other fields in a row, as 'Columns names are auto-discovered', how can i get all the columns for my ES's data, not just the first row's fields.

**Comment by sunyonggang** [comment]
![2015-08-31 11 34 55](https://cloud.githubusercontent.com/assets/3059266/9571701/7bd92ebc-4fd4-11e5-92a3-5344523280b7.png)

as you can see, the columns are listted only by the first data row, if the second data row has some fields that the first data don't have, it can't be recorded. so how to list all the columns if the rows have?

**Comment by wdavidw** [comment]
i dont really get it. as you stream new records, you expect new columns to be discovered. this isnt possible, you'll end up with csv lines of different column length. dont forget this parser stream data: csv output has been written as you receive new input objects. by the way, this question (if i understood it well) isnt related to this issue.

**Comment by sunyonggang** [comment]
sorry, my english is too bad, maybe i did not explain what i mean:
```
var columns = program.columns ? program.columns.split(',') : mappingKeys;
var stringifyOption = _.merge({ header: true }, { columns: columns });
var stringifier = stringify(stringifyOption);
```
before i fixed it, the columns was setted 'undefined', in the next time, i get the mappingKeys which is a mapping key list from a ES index & type, and then, it can work.

**Comment by wdavidw** [comment]
Could you write me a test by taking [example here](https://github.com/wdavidw/node-csv-stringify/blob/master/test/quote.coffee#L8-L17). Write what you expect and, if appropriate, i will make it work. This way, there wont be any confusion.
