### ISSUE TITLE
stringify: throw Error('Invalid column definition: property "key" is required');

### ISSUE THREAD

**Issue by rubyzhao** [adaltas/node-csv-stringify#101]
Take the example from https://csv.js.org/stringify/options/columns/
```
const stringify = require('csv-stringify');
const assert = require('assert');

stringify( [
    { a: '1', b: '2' }
  ], {
    header: true,
    columns: [ { 'a': 'col_a' }, { 'b': 'col_b' } ]
  }, function(err, data){
    assert.equals(data, 'col_a,col_b\n1,2\n')
  })

```
Will throw Error('Invalid column definition: property "key" is required');

By the way, if the columns option was changed to below:
`columns: [ { key: 'a', header: 'col_a' }, { key: 'b', header: 'col_b' } ]`
Then there is no any error.

**Environment:**

- csv: 5.1.3
- csv-stringify: 5.3.3
- Node: 12.11.1

**Comment by wdavidw** [comment]
Thank you for reporting, I have updated the documentation relative to the `columns` and `header` options. Also, all the sample are now tested.
