### ISSUE TITLE
Options for `stream.Transform` is not transferred from `Stringifier`

### ISSUE THREAD

**Issue by redexp** [adaltas/node-csv-stringify#104]
Hello, I found a bug in `Stringifier` class when it passes options to `stream.Transform`. 
https://github.com/adaltas/node-csv-stringify/blob/49f1dc3511b7cb1bb34bc04df880b18afa2236fb/lib/index.js#L98-L100
On first look it seems that `super` will get merged options from `Stringifier` but on that line `options` is `undefined` all the time. Maybe instead of `options` there should be `opts`? If not then basically code should be rewritten to `super({writableObjectMode: true})`.

**Comment by wdavidw** [comment]
Thank you for reporting, passing `opts` was the expected behavior
