### ISSUE TITLE
How can provide cast options when using the steaming API?

### ISSUE THREAD

**Issue by evantahler** [adaltas/node-csv-stringify#106]
This would be a great example to add!

**Comment by evantahler** [comment]
Ah! Everything is OK... my mistake!

Typescript correctly is mad when the response-type of a `cast` isn't a string, but the message it returns is a bit odd.  I'm casting Dates to be in UNIX timestamps, so dividing the JS ms integers by 1000, and I was returning a number and not a string:

```ts
import CsvStringify from "csv-stringify";

const csvStream = CsvStringify({
    header: true,
    columns,
    cast: {
      date: function(v) {
        return Math.round(v.getTime() / 1000); // <-- needs to be a string
      }
    }
  });
```

The error produced was:
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ header: boolean; columns: string[]; cast: { date: (v: Date) => number; }; }' is not assignable to parameter of type 'Input'.
      Object literal may only specify known properties, and 'header' does not exist in type 'Input'.ts(2769)
```

**Comment by wdavidw** [comment]
Yes, this idea is that since we end up with string, we enforce the string type on the user defined function instead of casting which would be more intrusive. Feel free to update the documentation (there is an edit icon on each page) if necessary.
