### ISSUE TITLE
stringify es5/sync does not work with objects

### ISSUE THREAD

**Issue by thmszheng** [adaltas/node-csv-stringify#109]
whenever I try to es5/sync stringify an array of objects it would throw an error. This is the error log:
![image](https://user-images.githubusercontent.com/56773282/79951850-505f3400-842e-11ea-9823-0b240472a1eb.png)

This simple example will show the above error
```
const stringify = require('csv-stringify/lib/es5/sync');
stringify([{'abc': 1}])
```

**Comment by wdavidw** [comment]
I just fixed it with a new release. This was due to the recent rewrite of the library from Coffee to JS where a variable was declared without its `const` prefix.
