### ISSUE TITLE
Stringify with the Same Rules as JSON.stringify

### ISSUE THREAD

**Issue by kcwitt** [adaltas/node-csv-stringify#111]
Feature request for CSV.stringify to have an option to stringify according to the same rules as the de-facto data transfer protocol JSON.stringify.

Regardless of whatever standards csv-stringify and csv-parse are built to, it would be useful to provide an option to force it to follow the same rules as JSON.stringify/parse.

The specific use case, is to reduce bandwith by sending a list of records over the wire in CSV format instead of JSON format (since in JSON format the field names are repeated for each record); and then using CSV.parse on the other side to get back the original fully inflated records.

The rules are pretty simple: quote anything that is a string or date, and don't quote anything that is a number or boolean (use true/false unquoted). Or in other words, quote anything that is quoted in the input, and don't quote anything that is not quoted in the input.

**Comment by wdavidw** [comment]
I understand the usage of CSV as an alternative to JSON but there is no reason to replicate anything from JSON. For bandwidth purposes, CSV is fine as it, it will only add quotes if it needs to escape a field or row delimiter. Why would you want to make it more complicated?

**Comment by kcwitt** [comment]
Definitely don't want to make anything more complicated - would prefer for everything to be compatible out of the box.

The documentation at https://csv.js.org/stringify/options/cast/ says that the default operation is to convert true/false to 1/0, which is the behavior that was causing me problems. I tried to write a custom cast, but the cast function can only return a string, obj, int, or null.

**Comment by wdavidw** [comment]
Yes, `cast` only expect string (an object being just a string in the value property plus additional local options).

My understanding is that you wish to differentiate the string `"1"` from the boolean `true` and the number `1`. Here is a solution to serialize the information:

```coffee
stringify [
  ['true', true, "1", 1]
], eof: false, escape: '\\', cast:
  boolean: (value) -> if value then "true" else "false"
  string: (value) -> value: value, quoted: true
, (err, data) =>
  # data is `"true",true,"1",1`
```

However, it does not provide you type information on deserialization.

**Comment by kcwitt** [comment]
I would like:
{ string: "true", int: 1, stringint: "1", true: true, false: false, trueString: "true" }
to stringify to:
"string", "int", "stringint", "true", "false", "trueString"
"true", 1, "1", true, false, "true"

the first column is a string because it is quoted,
the second is a number because it is not quoted
the third is a string because it is quoted
the fourth is a boolean with value true because it is not quoted
the fifth is like the fourth except false
the sixth is a string (not a boolean) because it is quoted

Of course it is possible to just convert an object into an array, and then JSON stringify/parse the array (of arrays), but I was trying to find a suitable standard instead method.

It is not that I want to differentiate "1", 1, and true, it is that I don't ever want true (or false) to be changed to anything else. Right now, when I put a true value into stringify it comes out as a 1 (which is a loss of type information).

**Comment by wdavidw** [comment]
This is what my suggestion returned, no ?

**Comment by kcwitt** [comment]
Ok, thank you very much

**Comment by kcwitt** [comment]
@wdavidw honestly, I didn't try what you had proposed, because I can convert an array of objects into an array of arrays with a one liner `.reduce` function. But days later, I am still wondering - why would cvs-stringify transform the data that was put into it at all ever for any reason (ie. change true/false to 1/0)? What is the reason to do that? Is it required by some standard or something?
