### ISSUE TITLE
specify different EOL character

### ISSUE THREAD

**Issue by aksharj** [adaltas/node-csv-stringify#113]
HI All,

I have the below code, where i am reading from source file and transforming and generating csv. the source files have EOL as `CRLF` but after transforming the EOL is `LF`. Is there a way i can have `CRLF` as my line ending?

```
        await pipelineAsync(
          fs.createReadStream(m.path),
          csv.parse({delimiter: '\t', columns: true}),
          csv.transform((input) => {
            return Object.assign({}, input);
          }),
          csv.stringify({header: true, delimiter: '\t'}),
          fs.createWriteStream(fname, {encoding: 'utf16le'})
        )
```

Any help on how to achieve this will be really helpful. Thanks.

**Comment by wdavidw** [comment]
Sorry I'm coming late on this one. Isn't `record_delimiter` suppose to do just that? In your case, you can set its value to `windows` or `\r\n'.
