### ISSUE TITLE
Text in UR-8 format does not open correctly in excel

### ISSUE THREAD

**Issue by laysearaujo** [adaltas/node-csv-stringify#118]
Text in UR-8 format does not open correctly in excel.

A clear and concise description of what the bug is, the CSV package version you are using.

csv-parse
NPM version 4.13.1

Please provide us with a unit test, an example code or even pseudo-code. It could be written in JavaScript or CoffeeScript, it doesn't matter. What's important is to limit the data to the minimum as well as to strip down the number of options to the only ones with an impact.

App with Quasar dev no response UR-8
```
function wrapCsvValue (val, formatFn) {
  let formatted = typeof formatFn !== 'undefined'
    ? formatFn(val)
    : val

  formatted = typeof formatted === 'undefined' || formatted === null
    ? ''
    : String(formatted)

  formatted = formatted.split('"').join('""')
  return `"${formatted}"`
}
```

**Comment by wdavidw** [comment]
Sorry but I can't help you with such a report. You don't provide any code related to the usage of this library. There is no description of your problem. I have no idea what UR-8 stands for, nor google.
