### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by kelly-tock** [adaltas/node-csv-stringify#122]
**Is your feature request related to a problem? Please describe.**
Currently using this to generate csv data for download client side, using webpack 4. in webpack 5, they removed all polyfills essentially, and I am not able to get this module working. I was able to polyfill most things minus `process.nextTick`, i'm wondering if there is a way to have a more agnostic version of this without node built ins?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wdavidw** [comment]
I search [`nextTick` inside the `lib` folder](https://github.com/adaltas/node-csv-stringify/search?q=nextTick&type=code) but couldn't find any occurence.

**Comment by wdavidw** [comment]
I have added the `lib/browser` modules which are generated with browserify along a demo inside [`samples/browser`](https://github.com/adaltas/node-csv-stringify/tree/master/samples/browser), it shall make your day.

**Comment by kelly-tock** [comment]
indeed it did!  thanks. yes, sorry for the bad description, but the nextTick part was from a polyfill for readable stream. 

https://github.com/nodejs/readable-stream/issues/450
