### ISSUE TITLE
is it possible to not cast string of array to array

### ISSUE THREAD

**Issue by raghu64** [adaltas/node-csv-stringify#124]
I have object with following structure 
`let data = [{
     a: '[1]',
     b: '[1,2,3]'
}]` 
and i'm trying to see if their is an option or flag that i can use to not convert the `'[1]'` to `[1]`

node: v10.16.0
csv-stringify: v3.1.1

https://runkit.com/embed/vo8e4y5ph976

**Comment by wdavidw** [comment]
Do you want to have `'[1']` in the final result, you could `let data = [{ a: "'[1]'", b: '[1,2,3]' }]`

**Comment by raghu64** [comment]
Thanks for the quick response. 

I'm pulling the data from a different service which send in `'[1]'` format for some fields, so i don't have enough exposure to the data to make the suggested changes.

**Comment by wdavidw** [comment]
From my undestand, the single quote are javascript quote, the parser only receive `[1]` so there is nothing it can do on its own. You can use the `cast` option to manipulate how the final field is rendered.

**Comment by raghu64** [comment]
Ok thanks. I'll try that.

**Comment by raghu64** [comment]
Hi @wdavidw , i tried to use cast and its working with latest version, but the current version that we are using is v3.1.1 and with this version it seems i can't get it to work. I tried both cast and formatters options.

https://runkit.com/embed/ffkhn2539pho

Any suggestion on how i can get this working?

**Comment by wdavidw** [comment]
Honestly, I have no memories of what is inside 3.1.1. You can [checkout into its associated tag](https://github.com/adaltas/node-csv-stringify/tree/7e3aa8ee772a037d7f352d946b8d0fe1d4430c3d) and looks throw the tests, the coverage is almost 100%, if there is a solution, you'll find it there. Looks at the [`type` test](https://github.com/adaltas/node-csv-stringify/blob/7e3aa8ee772a037d7f352d946b8d0fe1d4430c3d/test/types.coffee), there is a formater but I don't know if it will work for your case, it is the ancerster of `cast` but was less flexible.

**Comment by raghu64** [comment]
Thanks. It seems there is no option for string type in `formatters`.

I'll try to use the latest version where i can use `cast`.
