### ISSUE TITLE
Inline content disposition

### ISSUE THREAD

**Issue by adamreisnz** [adaltas/node-csv-stringify#51]
Hello, I am using this module to generate CSV (surprisingly), but I want it to be displayed in the browser instead of being downloaded as a file. From what I can see, there is no control over this. I have tried setting the `Content-Disposition` header manually to `inline` but to no avail.

Any thoughts? Current code is:

```js
    //Create stringifier
    const stringifier = csvStringify(options);

    //Pipe to response
    res.set('Content-Type', 'text/csv; charset=utf-8');
    res.set('Content-Disposition', 'inline');
    stringifier.on('finish', () => res.end());
    stringifier.on('error', next);
    stringifier.pipe(res);
```
Then looping items, writing lines and finishing with `stringifier.end();`.

**Comment by wdavidw** [comment]
no idea personnaly, anyone ?

**Comment by adamreisnz** [comment]
It may be my browser (Chrome) being stubborn, it does the same thing if I
don't pipe but just output csv content directly, with the same headers... :(

**Comment by adamreisnz** [comment]
So there's more issues related to this, not sure if I should create a separate ticket or carry on here, but it appears that when using the streaming API, content is cut off prematurely, and some CSV lines are lost in the final output.

This has happened in two separate projects so far, and it only happens when using the streaming API. When generating the CSV in advance in full and then downloading, all content is there. But obviously that's not a good solution for large data sets.

Do you want me to raise a separate ticket for this?

**Comment by wdavidw** [comment]
I dont believe this is related to the csv-stringify package. As far as I know, the Streaming implementation has been stable for many years. If you confirm we have an issue, then what I need first is simple exemple or test case, without anything related to http, illustrating and reproducing the issue.

**Comment by adamreisnz** [comment]
Hi @wdavidw, thanks, I'll try to make a reproducible example. I'm not sure at this stage where the problem lies, but we've experienced it in two different projects now, where the stream seems to be cut off prematurely before we've called `.end()`, or maybe it's csv-stringify which hasn't processed the last few added lines yet at that stage. I don't know enough about the internals of the csv-stringify package to judge that, but I'll see if I can put something together to demonstrate the issue.

**Comment by adamreisnz** [comment]
Alright, I managed to reproduce with a very basic example using only Express and CSV stringify;

```js
const express = require('express');
const app = express();
const csvStringify = require('csv-stringify');

const data = [
  {id: 123, title: 'Test', description: 'Test'},
  {id: 123, title: 'Test', description: 'Test'},
  //...
  //Repeat 900 times
  //...
  {id: 123, title: 'Test', description: 'Test'},
  {id: 123, title: 'Test', description: 'Test'},
};

//Define columns
const columns = [
	'id',
	'title',
	'description',
];

//Stringifier options
const options = {
	header: true,
	columns,
	delimiter: ',',
	quote: '"',
	trim: true,
};

//All at once
app.get('/all', (req, res, next) => {

	//Write lines
  const lines = data.map(item => {
    const {id, title, description} = item;
    return [id, title, description];
  });

	csvStringify(lines, options, (error, output) => {
    if (error) {
      return next(error);
    }

    //Output
    res.set('Content-Type', 'text/csv; charset=utf-8');
    res.set('Content-Disposition', 'inline');
    res.write(output);
    res.end();
  });
});

//Streaming
app.get('/stream', (req, res, next) => {

  //Create stringifier
  const stringifier = csvStringify(options);

  //Pipe to response
  res.set('Content-Type', 'text/csv; charset=utf-8');
  res.set('Content-Disposition', 'inline');
  stringifier.on('finish', () => res.end());
  stringifier.on('error', next);
  stringifier.pipe(res);

  //Write lines
  data.forEach(item => {
    const {id, title, description} = item;
    const line = [id, title, description];
    stringifier.write(line);
  });

  //End
  stringifier.end();
});

app.listen(3000, function () {
  console.log('App listening on port 3000')
});
```

Run, then browse to:

http://localhost:3000/all
http://localhost:3000/stream

The first link which pre-generates all of the CSV before outputting, will output the correct CSV with 900 lines of data.

The second link which uses streaming, will output a CSV with only 851 lines of data. This happens consistently. When you reduce the amount of data to say 150 lines, both output correctly.

As I said, I'm not too sure where the fault lies, but I hope this example will give you the ability to debug it. If it's an issue with the streaming API or Express, I'll be happy to raise the issue there.

Please let me know if you need anything else to investigate.

**Comment by wdavidw** [comment]
When you pipe to a stream writer, your http response, you do not need to call end, see the [pipe documentation](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options).

I just publish a [test](https://github.com/adaltas/node-csv-stringify/blob/master/test/api.pipe.coffee#L21-L33) that illustrate and validate your usecase, you can use it as an example but it is too different from what your alreading doing, just removing the call to end.

Note, writing data as you do and piping it is not scallable, you should provide a stream reader instead which will adjust to the speed of your stream writer.

**Comment by adamreisnz** [comment]
Thanks, will give it a go, and thanks for the heads up on the piping.

**Comment by adamreisnz** [comment]
Sorry was confused as to which `end` you meant, as in your example you are still calling `stringifier.end()` here https://github.com/adaltas/node-csv-stringify/blob/master/test/api.pipe.coffee#L29, and when I remove this from my code it never ends the request.

However, I've removed `stringifier.on('finish', () => res.end());` and that seems to have done the trick, thanks.

**Comment by wdavidw** [comment]
Old issue, closing.
