### ISSUE TITLE
Issue with UglifyJS

### ISSUE THREAD

**Issue by lewiswalsh** [adaltas/node-csv-stringify#58]
Been using this with Vue-CLI without issue until I tried to build the code and UglifyJS failed at two points,

`Stringifier = function(opts = {}) {  // index.js, line 97`
UglifyJS expects a comma where the equals sign is. This was my fix:
    Stringifier = function(opts) {
        if(!opts){ opts = {}; }

`chunk = `${chunk}`;  // index.js, line 260`
UglifyJS doesn't like the backticks. This was my fix:
`chunk = ''+ chunk;`

Let me know if you see any problems with this. Happy to create a pull request if you think it beneficial.

**Comment by wdavidw** [comment]
The js code is generated by CoffeeScript is modern JavaScript and it seems like UglifyJS doesnt handle it. You could use csv-stringify version 1.x which is aligned with version 2.x for now or transpile it with Bable. I'am also thinking about providing a backward compatible file with the version 2.x of this package but didn't took the time yet to package it.

**Comment by wdavidw** [comment]
Could you try downloading the latest version of this package and try importing modules from "./lib/es5", it should work now

**Comment by lewiswalsh** [comment]
That seems to have solved it. Thanks so much.
