### ISSUE TITLE
unexpected line break at end

### ISSUE THREAD

**Issue by emmettnicholas** [adaltas/node-csv-stringify#6]
```
stringify([['a','b'],['c','d']], function(err, output) {
    console.log(JSON.stringify(output));
});
```

results in `"a,b\nc,d\n"`

whereas I expected `"a,b\nc,d"`

**Comment by chadfawcett** [comment]
I also ran into this issue expecting no `\n' at the end of the file. It would be nice if the examples could be the same as the actual output.
