### ISSUE TITLE
Row Limit

### ISSUE THREAD

**Issue by jwerre** [adaltas/node-csv-stringify#63]
I've notice that when compiling my CSV the file is always truncated to 1089 rows even with different data being steamed. Any idea why that would be happening?

**Comment by wdavidw** [comment]
Are you consuming the stream ?

**Comment by wdavidw** [comment]
Closing since there is no more activty.

**Comment by mwgamble** [comment]
I've started to notice a similar issue. When a certain point is reached (in terms of how much data is written to the stream), additional rows get silently dropped. When this runs in AWS Lambda, the function crashes as a result.

> Are you consuming the stream ?

Would you be able to elaborate on why this is necessary, and some strategies for dealing with situations where it isn't practical to consume the stream as the same time it is being written?

**Comment by wdavidw** [comment]
This library extends/implements de stream.Transform API. It is both a stream.Writable and a stream.Readable. You write to it and your read from it. The reader tell the library if it can accept more incoming data to prevent being overflowed. If there is no reader consuming the stream, the library will wait for ever and only the first records are being handled. Please provide an exemple for furter help.
