### ISSUE TITLE
Can't get stream API to pipe

### ISSUE THREAD

**Issue by johnelliott** [adaltas/node-csv-stringify#66]
I cannot figure out how the stream API is supposed to work. This is not my first time using streams.

```
node v8.11.3
csv-stringify v3.1.1
```

My code:

```javascript
const debug = require('debug')('str')
const csvStringify = require('csv-stringify')

const stringifier = csvStringify({
  header: true,
  columns: { name: 'name', locality: 'locality' }
}).pipe(process.stdout)

stringifier.on('error', function (err) {
  debug(err.message)
})
stringifier.on('finish', function () {
  debug('finish')
})

// Waiting, could just use event but lazy
setTimeout(() => {
  stringifier.write(['john', 'world']) // Error, see below
  // This produces err, see below

  // stringifier.write(JSON.stringify(['john', 'world']))
  // // ["john","world"] <- json, not csv
}, 200)

```

Result
```
net.js:704
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at WriteStream.Socket.write (net.js:704:11)
    at Timeout.setTimeout [as _onTimeout] (/Users/john/code/csv-test/str.js:17:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

I don't understand what I am supposed to call `.write` with, or how the options might change what I am supposed to call write with. It seems like this module is just a no-op transform stream, but that can't be right.

What is wrong with this code?

Note: the sample code `// node samples/stream.js` from the website produces the same error

**Comment by yonilerner** [comment]
http://csv.adaltas.com/stringify/examples/

**Comment by johnelliott** [comment]
@yonilerner Thank you I have read that. Does the code run on your machine?

**Comment by yonilerner** [comment]
I think the main issue is that `stringifier` was assigned to the result from pipe, and I'm not sure that pipe functionality is implemented in that way (the example doesn't use it). I'm just a casual observer poking his nose where it doesn't really belong; I don't necessarily know anything.

**Comment by johnelliott** [comment]
Haha I just tried this too. I didn't give myself a reference to the function that had the write method. I expected pipe to return the transform/duplex stream that I could write to.

**Comment by yonilerner** [comment]
Yea taking a quick peek at the code, seems like `write` is overriden by the object returned from `csvStringify`, but in the end just returns `stream.Transform.prototype.write.call(..)`, which would be a native stream, not a csv-fancy one

**Comment by johnelliott** [comment]
Thanks @yonilerner 

I think it comes down to [this statement in the node docs](https://nodejs.org/dist/latest-v8.x/docs/api/stream.html#stream_readable_pipe_destination_options):
> The readable.pipe() method returns a reference to the destination stream making it possible to set up chains of piped streams

**Comment by wdavidw** [comment]
@johnelliott  you got it right!

**Comment by offero** [comment]
> ```js
> stringifier 
> ```

ffs my exact issue. Thank you!

**Comment by offero** [comment]
> Haha I just tried this too. I didn't give myself a reference to the function that had the write method. I expected pipe to return the transform/duplex stream that I could write to.

ffs my exact issue. Thank you!
