### ISSUE TITLE
order of headers

### ISSUE THREAD

**Issue by nanomosfet** [adaltas/node-csv-stringify#67]
I noticed that the header value only takes true, but it just takes the keys of the columns. You can't enforce the order of the keys in an object so I was wondering if there was anyway to enforce a specific order for the headers. If there isn't, I am willing to put in some work to get this feature out. (As they will probably ask me to order it anyway :P)

**Comment by wdavidw** [comment]
Seems workable. You can start by writting a few tests to make sure we are aligned.

**Comment by nanomosfet** [comment]
Sorry for the delay. I am not sure how I could test this. I think the only time this is applicable is when you get your object from an API. Otherwise if you define your object right before you pass it to csv stringify most node/JS will actually preserve insertion order and they will end up in the correct order. 

Any suggestions on how we can test this, as I am not sure how I can write a test that tests something undeterministic(such as the order of the keys in an object)

**Comment by wdavidw** [comment]
Definitely not recommended. This being said, never experience any change of order since I started with JS. I'll take a look now at the issue is see what I can do.

**Comment by jobe451** [comment]
This is very helpful, in fact, I changed some code on my side using even this pattern:

	stringify( {
	  { a: '1', b: '2' }
	}, {
	  header: true,
	  columns: [ 'a', 'b' ]
	}, function(err, csv){
	  assert.equals(csv, 'a,b\n1,2\n')
	})

Probably would be an overkill to also mention that one.

**Comment by wdavidw** [comment]
Well, it was ready but i forgot to commit, push, release. This is now available with version 4.1.0
