### ISSUE TITLE
can't output European format numbers

### ISSUE THREAD

**Issue by koenbeek** [adaltas/node-csv-stringify#68]
I need numbers to be output in format 1.000.000,00 EU format and not 1,000,000.00 (US)

It doesn't seem possible for the moment

Maybe use number.toLocaleString() or simply add an option for a specific number formatter so we can overload the number format

**Comment by wdavidw** [comment]
I just release a new version with a number formater. You can get inspiration from the [test](https://github.com/adaltas/node-csv-stringify/blob/master/test/options.formatters.coffee#L20-L25).
