### ISSUE TITLE
Escaping formula (CSV Injection)

### ISSUE THREAD

**Issue by michaeljones** [adaltas/node-csv-stringify#69]
We're a happy users of your library but it has recently been highlighted to us that we have issues with "CSV Injection". I haven't come across this before but it seems it means that we make no effort to escape any formula, commands or `|` characters in the inputs and that means that people could create CSV files that cause trouble when opened in Excel. 

I can't tell if a library such as yours should trouble itself with such a thing. I also can't tell if it is possible to use some of the available options to mitigate the problem. The advice we were given was that we should make sure:

> The input does not start with “=”, “+”, “-“ or “@”
> The input does not contain the pipe “|” character.

Some blogs about the topic suggest that prefixing the cell value with a [single quote](https://www.contextis.com/blog/comma-separated-vulnerabilities) or a [tab character](http://georgemauer.net/2017/10/07/csv-injection.html) is sufficient to avoid the problem.

I have tried to use the quote & escape options but I don't feel like it is enough. If I force double quotes around everything, then LibreOffice ignores them (I guess that is part of the CSV spec?). If I force single quotes then they are displayed in the spreadsheet in an unappealing manner.

I feel that from some experimentation that double quotes with an extra space at the front ahead of any entries with =, +, - or @ might be the way forward. Unfortunately it is not possible to provide a string formatter so I don't believe I can do that. 

That's kind of a summary of where I'm at. Sorry if this is all super basic and I'm missing something. I assume this has come up before but I'm not seeing anything in the docs or issues though I often miss things, so sorry if I have.

**Comment by michaeljones** [comment]
Hmm, I guess I'm being a bit of a fool. I could do all this before handing it to the CSV stringify call. I'll do that.

**Comment by michaeljones** [comment]
It is also misleading to call it "CSV Injection". Really it is Excel Injection (or LibreOffice.) 

That said, I would have found it useful to have a paragraph about this in the docs if you feel that is in any way sensible to add.

**Comment by wdavidw** [comment]
This issue was never raised before and I believed your are right that this is probably not an issue with this package directly. Using the `quoted` option might be the only part this package could offer. Open to suggestion if I'm proved wrong.
