### ISSUE TITLE
index.d.ts Options.columns type of PlainObject?

### ISSUE THREAD

**Issue by ryachza** [adaltas/node-csv-stringify#73]
My thinking is that the type of `Options.columns` should incorporate something like `{ key:string,header?:string }[]`. Am I misunderstanding the API or the definition of `PlainObject`? I'm receiving a type error when trying to pass something like `{ columns:[{ key:'a',header:'A' },{ key:'b',header:'B' }] }`:

    Type '{ 'key': string; 'header': string; }[]' is not assignable to type 'string[] | PlainObject<string> | undefined'.

**Comment by yonilerner** [comment]
This is indeed a mistake in the typings. It should be
```
columns?: string[] | PlainObject<string> | Array<{key: string, header?: string}>
```
I will submit a PR to correct this

**Comment by wdavidw** [comment]
Is this issue still valid ?

**Comment by yonilerner** [comment]
I think #74 should have resolved it

**Comment by wdavidw** [comment]
Thank you for the quick feedback
