### ISSUE TITLE
Cast and column index or column key

### ISSUE THREAD

**Issue by seimic** [adaltas/node-csv-stringify#76]
Hi,

ist there any way to get the index of the columns being formatted within the cast callbacks?
If one uses more than one formatting patterns for same type of data its difficult to 
decide, which format to take.

Example input: 
    `[{f00: 123.4, f01: new Date(), f02: newDate()}]`
Desired output:
    `[[ 123.40, 26.11.2018, 09:30 ]]`

At now I see only wrapper objects as solution and using the object cast.

    `[{ f00: 123.4, f01: { value: new Date(), format: 'DD.MM.YYYY'}, f02: { value: newDate(), format: 'HH:mm' }}]`

How you deal with such cases?

**Comment by wdavidw** [comment]
Latest version 5.1.0 introduces a [context](https://csv.js.org/stringify/options/cast/#context) object provided to the casting functions as the second argument. That shall fix your issue. Feel free to re-open otherwise.

**Comment by seimic** [comment]
This seems to be, what I was looking for. Thank you :-)
