### ISSUE TITLE
version 5.0.0 breaks bundle-collapser

### ISSUE THREAD

**Issue by cvlmtg** [adaltas/node-csv-stringify#77]
Hi, it seems csv-stringify 5.0.0 has some issues with browserify's bundle-collapser plugin. If I try to build my app with csv-stringify 5.0.0 I get this error:

```
[23:10:27] Starting 'build'... 
Main process exited with code 1
/Users/matteo/dev/html5-buttons/node_modules/falafel/node_modules/acorn/dist/acorn.js:2763 
  throw err
  ^

SyntaxError: Unexpected token (100:31)
    at Parser.pp$4.raise (/Users/matteo/dev/html5-buttons/node_modules/falafel/node_modules/acorn/dist/acorn.js:2761:13)
    at Parser.pp.unexpected (/Users/matteo/dev/html5-buttons/node_modules/falafel/node_modules/acorn/dist/acorn.js:647:8)
    at Parser.pp$3.parseIdent (/Users/matteo/dev/html5-buttons/node_modules/falafel/node_modules/acorn/dist/acorn.js:2716:10)
   etc...
```

the error isn't very helpful, so I added some console.log inside the `parseIndent` function and this is a piece of the output I got:

```
  input:
   '(function (Buffer,process){\n// Generated by CoffeeScript 2.3.2\n// # CSV Stringifier\n\n//
 Please look at the [project documentation](https://csv.js.org/stringify/) for additional\n// i
etc...
```

so I reverted to csv-stringify to 4.3.1 and now my app is building again.

**Comment by cvlmtg** [comment]
yeah, sorry, it was very late and I admit my issue didn't offer many informations :)

anyway, it's a syntax problem, as I have the error when creating the bundle with browserify, non when executing the code. this is how I create the bundle (with gulp)

```
  42   │ const babelOpts = {
  43   │   presets: [
  44   │     [ '@babel/preset-env', { useBuiltIns: 'entry' } ],
  45   │     '@babel/preset-react'
  46   │   ],
  47   │   plugins: [
  48   │     '@babel/plugin-proposal-logical-assignment-operators',
  49   │     '@babel/plugin-transform-runtime',
  50   │     [
  51   │       '@babel/plugin-proposal-class-properties',
  52   │       {
  53   │         loose: true
  54   │       }
  55   │     ]
  56   │   ],
  57   │   only: [
  58   │     'app/public/scripts/**/',
  59   │     'test/**/'
  60   │   ]
  61   │ };
  62   │ 
  63   │ const envifyOpts = {
  64   │   _:      'purge',
  65   │   global: true
  66   │ };
...
 309   │   const options = {
 310   │     extensions: [ '.jsx', '.js' ],
 311   │     debug:      !production
 312   │   };
 313   │ 
 314   │   const tasks = frontends.map((entry) => browserify(entry, options)
 315   │     .transform('babelify', babelOpts)
 316   │     .transform('envify', envifyOpts)
 317   │     .plugin(collapser)
 318   │     .bundle()
 319   │     .on('error', reportError)
 320   │     .pipe(source(entry))
 321   │     .pipe(buffer())
 322   │     .pipe(uglify().on('error', reportError))
 323   │     .pipe(rename({
 324   │       extname: '.min.js',
 325   │       dirname: ''
 326   │     }))
 327   │     .pipe(gulp.dest(dest)));
```

I either have to remove bundle collapser or use csv-stringify 4.3.1 to have browserify succeed. afaik bundle-collapser uses falafel, which uses acorn, to parse the bundle and modify it.

inside `node_modules/falafel/node_modules/acorn/dist/acorn.js`, line 2712, it's where the error get raised. If I add some logging I see that `node` (which I suppose is the AST node being processed) is `Node { type: '', start: 2770, end: 0 }` and it seems that the error is that `type` is just an empty string.

Digging a bit further it seems that position 2770 is inside `lib/index`, where it says:

```
  stream.Transform.call(this, {...options, ...{
      writableObjectMode: true
    }});
```

I tried to change it to

```
  stream.Transform.call(this, options);
```

and it works! the bundle get built without errors. I know my change is wrong, but I think it proves that acorn doesn't understand object destructuring, and I see you compile your code with coffeescript. could you try to see if you can convince coffeescript not to generate object detructuring code?

I see that bundle-collapser is using falafel 2.1.0, which is the latest version available, so trying to update acorn by updating falafel by updating bundle-collapser (which seems to be not very actively maintained...) is probably not the fastest way to solve the problem 😞 

thanks!

**Comment by wdavidw** [comment]
If you have your hand on the csv-stringify package, you should use "csv-stringify/lib/es5".

**Comment by cvlmtg** [comment]
that works, thanks!
