### ISSUE TITLE
cast / transformer unclarity

### ISSUE THREAD

**Issue by Shadowlauch** [adaltas/node-csv-stringify#78]
The TypeScript definitions and the samples in this repo mention 'transformers' in the options, but the website refers to 'cast'. Only cast seems to work, but throws an error in TypeScritp, because of the wrong decalaration.

**Comment by wdavidw** [comment]
Are you sure you mentioning the csv-stringify module and not csv-parse ?

**Comment by Shadowlauch** [comment]
I don't think so, but I'm not sure:

The github page links to the following docs: https://csv.js.org/stringify/options/ there it mentions the "cast".  Also in the changelog https://csv.js.org/stringify/changelog/ it mentions that the property was renamed to cast from formatters. But the options cast sample (https://github.com/adaltas/node-csv-stringify/blob/master/samples/option.cast.js) and the Options type in the TS definitions (https://github.com/adaltas/node-csv-stringify/blob/master/lib/index.d.ts) still mention formatters instead of cast.

**Comment by wdavidw** [comment]
It seems like you are using an older version (4.3.1 or below). As for the TS defition, it shall be fine with the latest release, otherwise you may open a new issue.

**Comment by wdavidw** [comment]
Sorry, I closed before your comment appears. I will fix the doc and sample today.
