### ISSUE TITLE
how can I skip an index?

### ISSUE THREAD

**Issue by JohnAllen** [adaltas/node-csv-stringify#83]
How can I effectively skip by index and not write an extra comma in my CSV?  have tried return false, null, empty string, etc.

Something like this:

```
string: (value, context) => {
        const ind = context.index
        const ignoreIndices = [17, 18, 19, 27, 28, 29, 37, 38, 39, 47, 48, 49, 57, 58, 59]
        if (ignoreIndices.indexOf(ind) > -1)
          return false
        if (value === '')
          return '0.'
}
```

**Comment by wdavidw** [comment]
Could you write me a small sample, it would help to clarify your request.

**Comment by JohnAllen** [comment]
updated

**Comment by wdavidw** [comment]
That was quick :)

**Comment by JohnAllen** [comment]
ha so were you!

**Comment by JohnAllen** [comment]
Basically I have a collection of objects and want to ignore certain fields on most of them (removing them from the DB would result in later adding them back).  I combine multiple objects into the array that I want to write to my CSV.

**Comment by JohnAllen** [comment]
I can just remove them right before I call `stringifier.write(...)` I suppose instead

**Comment by wdavidw** [comment]
I don't think you can at the moment (but i need to double check). The recommended approach at the moment is to prepare your dataset with [stream-transform](https://csv.js.org/transform/) before calling stringify. I'm not against adding a new feature otherwise, like handling `null` and `undefined` as such.

**Comment by wdavidw** [comment]
For exemple, currently:

```coffee
stringify [
  {a: true, b: true}
  {a: false, b: true}
  {a: true, b: false}
  {a: false, b: false}
], {cast: boolean: (value) -> if value then '1' else null}, (err, data) ->
  data.should.eql """
  1,1
  ,1
  1,
  ,
  
  """
```

while we could expect this instead:

```coffee
stringify [
  {a: true, b: true}
  {a: false, b: true}
  {a: true, b: false}
  {a: false, b: false}
], {cast: boolean: (value) -> if value then '1' else null}, (err, data) ->
  data.should.eql """
  1,1
  1
  1,
  
  
  """
```
