### ISSUE TITLE
.d.ts property doesn't match js - rowDelimiter should be recordDelimiter

### ISSUE THREAD

**Issue by Osipion** [adaltas/node-csv-stringify#84]
The [.d.ts indicates](https://github.com/adaltas/node-csv-stringify/blob/master/lib/index.d.ts#L90) that the row delimiter may be set with the option 'rowDelimiter: "windows"'. However, the underlying js file [only looks at recordDelimiter](https://github.com/adaltas/node-csv-stringify/blob/master/lib/index.js#L199) (or record_delimiter once the `underscore` function has snake_cased the property names). This leads to confusing behaviour for Typescript users.

**Comment by yonilerner** [comment]
@Osipion Good catch.

@wdavidw Resolved here: https://github.com/adaltas/node-csv-stringify/pull/85

**Comment by wdavidw** [comment]
Thank you both!
