### ISSUE TITLE
Null vs Empty string values

### ISSUE THREAD

**Issue by slacroix** [adaltas/node-csv-stringify#86]
There doesn't seem to be a combination of options that produces an empty value for null and a empty quoted value for an empty string. Null and empty string are treated the same for string types. I wouldn't mind making a PR if there is a decent way to approach that problem. Is there a way to add it without a breaking change?

**Comment by wdavidw** [comment]
Did you saw the [`quoted_string` option](https://github.com/adaltas/node-csv-stringify/blob/master/test/option.quoted_string.coffee#L19-L35), it seems to fit your request ?

**Comment by wdavidw** [comment]
Closing since there was no answer/activty.
