### ISSUE TITLE
2 replaces 'true' when quoted_string is true

### ISSUE THREAD

**Issue by jwerre** [adaltas/node-csv-stringify#87]
When you using the `quoted_string` option 'true' is always replaced with the number 2. For example:

	const assert = require('assert'),
		{stringify} = require('csv'),
		data = [
			{ 
				binary_false: 0,
				binary_true: 1,
				boolean_true: true,
				boolean_false: false,
				string_true: 'true',
				string_false: 'false',
			},
		],
		options = { 
			header: true,
			columns: Object.keys(data[0]),
			escape: true,
			quoted_empty: true,
			quoted_string: true, // <<-- change this to false and it will pass
		};

	
	
	stringify( data, options, function(err, data){
		
                 console.log(data);
		// "binary_false","binary_2","boolean_2","boolean_false","string_2","string_false"
		// 0,1,1,"","2","false"

		assert.equal( data.indexOf('2'), -1 );
		done();
	});

**Comment by wdavidw** [comment]
The escape option must be a string or null/undefined. I've just release version 5.2.0 which enforce a stronger validation on this option, I will also update the website which didn't provide much information.
