### ISSUE TITLE
Avoid escaping when using specific casting 

### ISSUE THREAD

**Issue by ozomer** [adaltas/node-csv-stringify#88]
I'm trying to generate a csv that sometimes contains numbers with a leading zero (i.e. local phone numbers).
These numbers are saved as strings (i.e. '012345') and are saved in the csv including the leading zero (as expected), but when this csv is loaded in Google-Sheets, the zero digit is removed (i.e. converting it to '12345').
I would like to be able to detect this case and save `="012345"` in this case.
However, since the casting happens before the escaping, if I try doing something like:
```
csvStringify(data, {
  cast: {
    string: value => (/^0\d+$/.test(value) ? `="${value}"` : value)
  }
});
```
the result would be `"=""012345"""`.
It would great to have a way in specific castings to disable the escaping (set the escape option to an empty string for this specific case). This can be implemented, for example, by making the cast-function return an object instead of a string:
```
csvStringify(data, {
  cast: {
    string: value => (/^0\d+$/.test(value) ? { value: `="${value}"`, escape: "" } : value)
  }
});
```

Right now, if the cast-function returns an object, a Formatter Error is thrown, so there are no backward-compatibility issues here.

Thanks!

**Comment by wdavidw** [comment]
I understand that your suggestion but I'm kind of reluctant to complexify the API, it is hard to document clearly and often end up with new issues on GitHub. Couldn't you simply disable "quote" and handle the quote and escaping on your side?

**Comment by ozomer** [comment]
I cannot control a "per-cell" quote, so I cannot just disable the "quote".
Another solution is to have a global configuration `avoidQuotingPrefix` so, for example, if the value is "<mark-817684763874>" any string like `<mark-817684763874>="012345"` will be converted to `="012345"` without quoting/escaping.

**Comment by wdavidw** [comment]
OK for the feature, would you feel like contributing ?

**Comment by ozomer** [comment]
Please have a look: https://github.com/adaltas/node-csv-stringify/pull/89

**Comment by wdavidw** [comment]
Closing since it was implemented recently and [documented on the website](https://csv.js.org/stringify/options/cast/#field-level-options)
