### ISSUE TITLE
quoted_match not working with cast number

### ISSUE THREAD

**Issue by n-peugnet** [adaltas/node-csv-stringify#91]
Hi, I have a problem with the usage of quoted_match option when used in combination with cast option.

First I was expected that quoted_match would be run after the cast so that the result of the following code would be:
```
montant_TTC;total_HT;commentaire
"12,54";9;"J'ai dégusté, et ça n'est pas forcément une bonne chose !"
```

```js
const stringify = require('csv-stringify');

let parameters = {
  columns: [
    'montant_TTC',
    'total_HT',
    'commentaire',
  ],
  data: [
    {
      montant_TTC: 12.54,
      total_HT: 9,
      commentaire: 'J\'ai dégusté, et ça n\'est pas forcément une bonne chose !',
    }
  ]
}

let options = {
  header: true,
  columns: parameters.columns,
  delimiter: ';',
  cast: {
    number: function(value) {
      return value.toString().replace('.', ',');
    },
  },
  quoted_match: /,/,
};

stringify(parameters.data, options, (err, csv) => {
  console.log(csv);
});
```

instead I get:
```
montant_TTC;total_HT;commentaire
12,54;9;"J'ai dégusté, et ça n'est pas forcément une bonne chose !"
```

Secondly, as I thought that it was a problem of order of execution I then tried to change the cast option like this:
```js
cast: {
    number: function(value) {
      return {value: value.toString().replace('.', ','), quoted_match: /,/};
    },
  },
```
but the result remains the same, so this option does not seem to work when used in the cast function.

For now I am resolving this issue using the option `quoted: true` in the cast function but it's not ideal as it adds a lot of unnecessary quotes in the csv.

**Comment by wdavidw** [comment]
Thank you for your report, you help me stop two issues:
- `cast` is called before `quoted_match` but `quoted_match` was only applying on string value while yours was a number, this was a mistake
- local options returned by cast where not validated and normalized, they are now.
