### ISSUE TITLE
recordDelimiter should be documented instead of record_delimiter

### ISSUE THREAD

**Issue by Congelli501** [adaltas/node-csv-stringify#92]
As all options are camel case, it would make more sense to use `recordDelimiter` instead of `record_delimiter`.
As both seems to work, the doc should state `recordDelimiter`.

If I'm mistaken and there is a reason behind the snake case usage, I'm curious :)

**Comment by wdavidw** [comment]
I personnaly prefer snake case and planning to use snake case everywhere like we're currently doing in csv-parse
