### ISSUE TITLE
Deprecated lodash.get dependency

### ISSUE THREAD

**Issue by skeggse** [adaltas/node-csv-stringify#93]
Per https://github.com/adaltas/node-csv-stringify/pull/71, `lodash.get` is deprecated. If `lodash` releases a security patch for `_.get`, it won't reach `node-csv-stringify`. The solution proposed in #71 may introduce too much overhead for this package, yet I still feel we should solve this some other way, as depending on a [deprecated package](https://github.com/lodash/lodash/issues/3744#issuecomment-409127068) can introduce problems down the road (especially in a class of packages that occasionally [contain flaws](https://www.npmjs.com/advisories/782)).

**Comment by wdavidw** [comment]
I will just import the `_.get` function. If someone has the time to prepare a pull request, i will review it. I dont have much time at the moment.

**Comment by tusbar** [comment]
That is even worse than depending on `lodash.get`.

I’m using `csv-stringify` in a lot of client-side apps (with webpack), `_.get` is still duplicated.

This library is already transpiled, you could use `coffee-loader` or a rollup equivalent to treeshake the unneeded parts of `lodash`.

But IMO it is a bad idea to break the dependency.

**Comment by wdavidw** [comment]
@tusbar I understand and agree with your statements. There are also pro to justify my decision. Not everyone is having lodash already loaded, it for small and well defined functionnality of the library, and I always wanted to keep this library free from external dependencies.
