### ISSUE TITLE
Writing a UTF BOM string throws error

### ISSUE THREAD

**Issue by dgollub** [adaltas/node-csv-stringify#94]
In our application we up until recently used version `3.1.1` of this library.

After upgrading to the latest version `5.3.0`, it started to throw an exception with the code below

```
const UTF_BOM = '\ufeff';
...
csvStream = csvStringify({ record_delimiter: 'windows' });
csvStream.write(UTF_BOM); // <<--- this now throws!
```

The **exception** is 

```
Uncaught Error: Invalid Record: expect an array or an object, got "﻿"                                            
      at Stringifier._transform (node_modules/csv-stringify/lib/index.js:277:23)                                      
      at Stringifier.Transform._read (_stream_transform.js:190:10)
      at Stringifier.Transform._write (_stream_transform.js:178:12)                                                   
      at doWrite (_stream_writable.js:410:12)                                                                         
      at writeOrBuffer (_stream_writable.js:394:5)                                                                    
      at Stringifier.Writable.write (_stream_writable.js:294:11) 
....
```

This is due to the newly added code [here](https://github.com/adaltas/node-csv-stringify/blob/bb09e629802ddedbd8df520c269317817dded6b6/lib/index.js#L101):

```
super({...{
        writableObjectMode: true
      }, ...options});
```

**Why do we need to write the BOM to the stream?** Because our (Japanese) clients use Windows with Excel and that expect the BOM, otherwise they end up with [mojibake](https://en.wikipedia.org/wiki/Mojibake) in their spreadsheet.

**Question: what is the recommended way to solve this issue and write the UTF BOM mark with this new version of csv-stringify?**

Can we have, by any chance, a constructor option to overwrite setting `writableObjectMode` to `true`? That would likely already solve the issue for my team (and our clients), is our best guess right now.

Thanks.

PS: We did try using the in-between version `4.3.1` of the library, but that one ends up throwing just a different error at a different place, so it is unusable as well:

```
Debug: internal, implementation, error                                                                                
    Error: Cannot reply with stream in object mode                                                                    
    at module.exports.internals.Response._marshal (/Users/dkg/projects/aiscanrobo-api/node_modules/hapi/lib/response.js:539:28)
    at exports.content (/Users/dkg/projects/aiscanrobo-api/node_modules/hapi/lib/headers.js:46:24)
    at Object.internals.marshal (/Users/dkg/projects/aiscanrobo-api/node_modules/hapi/lib/transmit.js:46:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by wdavidw** [comment]
Sorry, I missed your issue. Your instance of csv-stringify is a both a Stream writer and reader. You write records to it and it reads csv text. This csv text is then pass to another stream writer which is the one to start with the BOM if you wish to.

**Comment by dgollub** [comment]
Thanks for getting back to me.

Since I didn't want to spend a lot of time trying to find a solution, I (for now) decided to rollback to  version 3.1.1 of csv-stringify.

I did try your suggestion of using a second stream and piping the csv-stringify to it after writing the BOM into it, however somehow that didn't work. Most likely I did something wrong, but it has been some time since I tried that and I, unfortunately, do not remember the details anymore.

I will give it another look next time I upgrade our npm packages on the projects where this is relevant.

Thanks. You may close this ticket.

**Comment by Alan-Liang** [comment]
These code solved the issue for me:
```javascript
import { Transform } from 'stream'
import stringify from 'csv-stringify'

const bom = Buffer.from('EFBBBF', 'hex')
class AddBomTransform extends Transform {
  constructor (stream, options) {
    super(options)
    stream.pipe(this)
    // FXXX MICRO$OFT, see: https://stackoverflow.com/questions/15685053/save-csv-with-bom
    this.push(bom)
  }
  _transform (chunk, _encoding, callback) { callback(null, chunk) }
}
// to use:
const stringifier = stringify()
writeTo(stringifier)
return new AddBomTransform(stringifier)
```

**Comment by wdavidw** [comment]
Version 5.4.0 introduce a new `bom` option answering the problem raised by this issue.
