### ISSUE TITLE
Since the update to 5.3.2, columns with periods don't work

### ISSUE THREAD

**Issue by gcampax** [adaltas/node-csv-stringify#98]
Since the update to 5.3.2 (or perhaps 5.3.1), if an object is written where the key contains ".", nothing is printed out.

Simple test case:
```
const stringify = require('csv-stringify');
const out = stringify({ header: true });
out.pipe(process.stdout);
out.write({ 'foo.bar' : '1' });
out.write({ 'foo.bar' : '2' });
out.end();
```
should print:
```
foo.bar
1
2
```
actually prints:
```
foo.bar


```
(two empty lines)

**Comment by wdavidw** [comment]
Sorry for the inconvenience, fix in version 5.3.3
